{% set name = "sqeleton" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqeleton-{{ version }}.tar.gz
  sha256: 1e61c66cef86119738df1a85524b0c3e7b5147d6558e29f0c89699fb5abfcdf1

build:
  entry_points:
    - sqeleton = sqeleton.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - runtype >=0.4.2,<0.5.0
    - dsnparse
    - click >=8.1,<9.0
    - rich
    - toml >=0.10.2,<0.11.0
    # Needed for CLI
    - prompt_toolkit >=3.0.36,<4.0.0

test:
  imports:
    - sqeleton
  commands:
    - pip check
    - sqeleton --help
  requires:
    - pip

about:
  home: https://github.com/erezsh/sqeleton
  summary: Python library for querying SQL databases
  doc_url: https://sqeleton.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
