{% set name = "sqeleton" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqeleton-{{ version }}.tar.gz
  sha256: ae67275c1c886ac603495aee1317b27f973154acbc7d50f75a5c64ae82f815fa

build:
  entry_points:
    - sqeleton = sqeleton.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0
    - click >=8.1,<9.0
    - dsnparse
    - rich
    - runtype >=0.2.6,<0.3.0
    - toml >=0.10.2,<0.11.0

test:
  imports:
    - sqeleton
  commands:
    - pip check
    - sqeleton --help
  requires:
    - pip

about:
  home: https://github.com/datafold/sqeleton
  summary: Python library for querying SQL databases
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
