{% set name = "sqeleton" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqeleton-{{ version }}.tar.gz
  sha256: dd1995fb1297774ab72cbe153e657d41fd56cf926b424f5e1842b96d5c42961c

build:
  entry_points:
    - sqeleton = sqeleton.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - runtype >=0.5.0
    - dsnparse
    - click >=8.1
    - rich
    - toml >=0.10.2
    # Needed for CLI
    - prompt_toolkit >=3.0.36

test:
  imports:
    - sqeleton
  commands:
    - pip check
    - sqeleton --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/erezsh/sqeleton
  summary: Python library for querying SQL databases
  doc_url: https://sqeleton.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
